name: moviemate_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_database: ^10.5.0
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  equatable: ^2.0.5
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/moviemate_logo.jpg